### ISSUE TITLE
Update API for Generating Evaluations - also update evaluation_result status to Ongoing

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#100]
**DESCRIPTION**

- This is related to [Create API for Generating Evaluations#27](https://github.com/nerubia/kh360-nodejs/issues/27)
- After updating evaluation_administration status to 'Ongoing', also set all the related `evalution_result` records `status` to `Ongoing`

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/108

**Comment by sheilaramas** [comment]
OK verified
