### ISSUE TITLE
Migration for DB Changes for External Evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#102]
**DESCRIPTION**

- Make the following migrations to support external evaluators feature

          
- [x] Add new table: `external_users` with the following fields:
                    - id (auto assigned)
                    - email (required)
                    - first_name (required)
                    - middle_name
                    - last_name (required)
                    - role (varchar)
                    - company  (varchar)
                    - created_by
                    - updated_by
                    - created_at
                    - updated_at

- [x] Update `evaluations` table, add the following fields:
                    - `is_external`, boolean, default false, after submitted_date
                    - `external_evaluator_id`, this will be related to external_users table, default null, put this field after is_external

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/114
