### ISSUE TITLE
Create API to add external evaluators to Evaluation Administration

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#105]
**DESCRIPTION**

- [x] Create API to add evaluations and other related records to the Evaluation Admin
- [x] This API will be called from:
          - after Adding External Evaluator is clicked from Step 4
          - after Adding External Evaluator from List from Step 4

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/141
