### ISSUE TITLE
Create API to add, update, delete and retrieve data for  external evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#106]
**DESCRIPTION**

- This API will be used for managing external evaluators data
- Save data in external_users table
- Fields are as follows:
          - id (auto assigned)
          - email (required)
          - first_name (required)
          - middle_name
          - last_name (required)
          - role
          - company
          - created_by
          - updated_by
          - created_at
          - updated_at

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/117

**Comment by sheilaramas** [comment]
OK verified basic functions. Will create separate tickets if there are other issues.
