### ISSUE TITLE
Create API for Performance Evaluation Step 2B - Save & Proceed Action

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#11]
**Acceptance Criteria:**

Create and API for to save the data in Step2:
- insert new records in `evaluation_results` table, 1 record per employee selected. 
- Set the following fields:
                      - evaluation_administration_id
                      - user_id
                      - status = For Review (changed to For Review instead of Pending)
                      - created_by_id = user_id of admin who logged in
                      - updated_by_id = user_id of admin who logged in
                      - created_at = current date
                      - updated_at = current date
- set the other fields to either null or blank

**Validations:**
- Must have at least 1 employee selected

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/22

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/25

**Comment by sheilaramas** [comment]
**ISSUES**

- [ ] When going back to Step 2 from Step 3 and clicking proceed, another set of records are inserted in evaluation_results table resulting to duplicates.
- [ ] It should only insert if it was not previously inserted.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/81
