### ISSUE TITLE
Create API for SAVE for Performance Evaluation Form

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#115]
**DESCRIPTION**

- We will be changing the implementation for Performance Eval Form.. instead of saving every time the evaluator rates per criteria, saving will only be done if the evaluee will click on SAVE or SAVE & SUBMIT
- So for this change, we will need to create an API that will save the data in Performance Evaluation Form
- For this API, do the following:
          - [ ] Save all the ratings set by the evaluator
          - [ ] Save the comments
          - [ ] Set evaluation.status = `Ongoing`

**Comment by emmaacha** [comment]
PR: #120

**Comment by sheilaramas** [comment]
**ISSUES**

- [ ] please update the value for updated_at based on current date and time

**Comment by emmaacha** [comment]
#138
