### ISSUE TITLE
Update API for SUBMIT for Performance Evaluation Form

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#116]
**DESCRIPTION**

- We will be changing the implementation for Performance Eval Form.. instead of saving every time the evaluator rates per criteria, saving will only be done if the evaluee will click on SAVE or SAVE & SUBMIT
- So for this change, we will need to update the API that is used when clicking SUBMIT in Performance Evaluation Form
- For this API, do the following:
          - [ ] Save all the ratings set by the evaluator
          - [ ] Save the comments
          - [ ] Continue with all the other processes performed during submit (e.g. update status of evaluation to SUBMITTED, compute results etc)

**Comment by emmaacha** [comment]
PR: #120

**Comment by sheilaramas** [comment]
**ISSUE**

- [ ] When saving data for evaluation_ratings, please update also updated_at based on current date and time

**Comment by emmaacha** [comment]
PR: #138

**Comment by sheilaramas** [comment]
OK verified
