### ISSUE TITLE
Performance Evaluation Form - Evaluee Display if no Project and Role

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#118]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/666fb198-b6b2-4df6-84c9-ce3c74d54641)

- For Evaluations that are not linked with project_member records (no project_id and project_member_id), first check their templates. 

- [x] If their templates have evaluee role, then display the role name (you can get the name based on project_roles table)
- [x] If their templates have no evaluee role, then display the display name (evaluation_template.display_name)

**Comment by emmaacha** [comment]
FE PR: [#156](https://github.com/nerubia/kh360-react/pull/156)
BE PR: [#139](https://github.com/nerubia/kh360-nodejs/pull/139)

**Comment by sheilaramas** [comment]
OK verified
