### ISSUE TITLE
Update API for generating Evaluation records

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#121]
**DESCRIPTION**

1. When saving new data to Evaluations table, please set the following fields also:

- [x] created_at -> based on current date
- [x] submission_method -> just set to NULL initially
- [x] is_external -> set to 0 (for internal evaluators) and 1 if external evaluators

2. When updating Evaluations table (any update), please set the following fields:

- [x] updated_at -> based on current date when the update was done

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/128

**Comment by sheilaramas** [comment]
OK verified
