### ISSUE TITLE
Switch the sending of emails during Evaluation Administration to batch process

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#123]
**DESCRIPTION**

- Since processing for sending of emails might take time, we will transfer this process to backend.
- Please do the following changes:

- [x] Originally, during ADMINISTER EVALUATION process, if current date is within administration schedule, status for evaluation_administration will be set to Ongoing. Please change this and set to 'Processing' instead. Continue to perform all other steps except the one related to email.
- [x] For sending of emails, create a batch process that will do the following:

1. Get all evaluation_administration records whose status is `Processing`.
2. Perform sending of email tasks.
3. Set evaluation_administration status to `Ongoing`.

- [x] Set this new batch process to run every hour. (but for the purpose of testing, please set this temporarily to every 10 mins). We will switch back to every hour once we deploy to live.

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/144
BE: https://github.com/nerubia/kh360-nodejs/pull/131

**Comment by sheilaramas** [comment]
Closing this ticket. Did preliminary testing.
