### ISSUE TITLE
Create API to close Evaluation Administration

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#133]
**DESCRIPTION**

- Create API that will close evaluation administration.
- Evaluation Administrations can only be closed if status is Ongoing.
- Do the following for this API:

- [x] Set evaluation.status = `Expired` for each related evaluation record whose status is `Pending`, `Open`,  and `Ongoing`.
- [x] Get all related evaluation_results whose status is `Ongoing`. Loop through each of these records, do the following:
          - retrieve all evaluation records based on each evaluation_result whose status is submitted
          - compute the overall score
          - set status of evaluation_result to `Completed`

- [x] Set status of evaluation_administration record to `Closed`

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/151
BE: https://github.com/nerubia/kh360-nodejs/pull/135

**Comment by sheilaramas** [comment]
**ISSUES**

- [ ] Status was still set to `Expired` even if the status was `Submitted`
- [ ] No score computed for evaluation results

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/189

**Comment by sheilaramas** [comment]
**ENHANCEMENTS**

For this criteria, update to include status = For Removal

- [ ] Set evaluation.status = Expired for each related evaluation record whose status is Pending, Open, Ongoing and **`For Removal`**.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/273

**Comment by sheilaramas** [comment]
ok verified
