### ISSUE TITLE
Create Migration for external_users table

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#145]
**DESCRIPTION**

- Update the external_users table and add the following fields (after company field):

- [ ] authentication_token (varchar)
- [ ] password
- [ ] failed_attempts (int)
- [ ] locked_at (datetime)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/148

**Comment by sheilaramas** [comment]
@jatnerubia  this is not yet migrated to Beta?

**Comment by jatnerubia** [comment]
@sheilaramas done ^^

**Comment by sheilaramas** [comment]
OK, for reference, fields updated as follows:

- [ ] access_token (varchar)
- [ ] code
- [ ] failed_attempts (int)
- [ ] locked_at (datetime)
