### ISSUE TITLE
Update answer_options table to add answer_type.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#150]
**DESCRIPTION**

- [x] Add new field to be used to determine answer type. Add `answer_type`, string, after `display_name`, `default = null`.
- [x] Also create a seeder to set answer_option_id records:
            - 1: answer_type = `na`, rate = 0;
            - 2: answer_type = `lowest`
            - 6: answer_type = `highest`

**Comment by emmaacha** [comment]
PR: #155

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] Please set rate of NA to 0 also. Currently, it was not set.

**Comment by emmaacha** [comment]
PR: #184

**Comment by sheilaramas** [comment]
OK Verified
