### ISSUE TITLE
Create seeder for Performance Evaluation Request for Comments

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#157]
**DESCRIPTION**

- Create seeders for modal box messages requesting for comments for various scenarios to be used in Evaluation Form.

- [x] NA (template_type = 'Performance Evaluation NA Rating')
- [x] High Ratings (template_type = 'Performance Evaluation High Rating')
- [x] Low Ratings (template_type = 'Performance Evaluation Low Rating')

- Refer to this [link](https://docs.google.com/spreadsheets/d/1o1Fysn56loca4hLThEK6QinoxrW5CVDxzNAz3wJWXOI/edit#gid=1988291839) for the data.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/159

**Comment by sheilaramas** [comment]
OK verified
