### ISSUE TITLE
Create Email Template for external user resend verification code.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#161]
**DESCRIPTION**

- Create seeder for Resend Verification Code email
- Contents as follows:

- [ ] Name: Reset Verification Code Email
- [ ] Template Type: Reset Verification Code
- [ ] Default: Yes
- [ ] Subject: Your KH360 Verification Code
- [ ] Content:

```
We recently received a request for a new verification code.
Your verification code is: {{verification_code}}

Please use this code to complete the Performance Evaluation Form. If you didn't request this code or are experiencing any issues, feel free to contact our HR Team at hr@nerubia.com.

Thank you.
```

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/163

**Comment by sheilaramas** [comment]
ok verified
