### ISSUE TITLE
Create API to retrieve data for Evaluation Admin Progress Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#162]
**DESCRIPTION**

- Create API to retrieve Evaluation Administration data and progress for each evaluators
- Information needed are as follows:

- [x] Evaluation Administration Data
- [x] List of all evaluators for this administration
- [x] For each evaluators, get the following:
          - evaluation progress (how many already submitted vs how many evaluation forms to fill up in all)
          - list of evaluation information

- Please refer to wireframe below for an idea on the information that are needed:

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/63bef896-8929-468d-8239-47066931fa56)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/188

**Comment by sheilaramas** [comment]
OK verified. Will create a separate ticket if there are issues related to this.
