### ISSUE TITLE
Create API to send reminder email for evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#165]
**DESCRIPTION**

- [x] Create an API that will send an email for evaluators reminding them of their pending performance evaluations
- [x] Use template for Performance Evaluation Reminder Email
- [x] This API will be called when ADMIN clicks on NUDGE link in Evaluation Administration Progress Screen
- [x] The email template contains placeholder for list of evaluees
- [ ] For evaluee list, get list of evaluations that are not yet submitted and get distinct evaluee names
- [x] Format for evaluee list should be `- last_name, first_name`
- [x] Example:
          - Echiverri, Sheila
          - Lerit, Jason
          - Acha, Catriona

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/171
