### ISSUE TITLE
When evaluation administration is closed or cancelled, delete all evaluation records whose status is Excluded

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#170]
**DESCRIPTION**

- [x] Once and evaluation admin is cancelled or closed, delete all evaluation records whose status = Excluded. This is so we can clean up records that are no longer needed.
- [x] Please include this routine in API's for closing and cancelling.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/180

**Comment by sheilaramas** [comment]
Verified for CLOSE action

**Comment by sheilaramas** [comment]
OK verified for CANCEL action.
