### ISSUE TITLE
Evaluation Form - change computation for N/A.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#173]
**DESCRIPTION**

- If answer is NA (base this on answer_option.answer_type), set percentage in evaluation_ratings to 0.

**Comment by emmaacha** [comment]
PR: #183

**Comment by emmaacha** [comment]
PR: [#187](https://github.com/nerubia/kh360-nodejs/pull/187)

**Comment by sheilaramas** [comment]
Can you please set the percentage to 0 only if all validations for the answers are passed?
Currently, some validations did not pass so the evaluator is redirected back to the screen to correct it.
What happens is that the evaluator can still edit the N/A and change to actual ratings.
So when the form is finally submitted, the percentage (0) was followed.

The safest approach here is to only set to 0 after all validations, so that you no longer have to set and reset the percentage value when user clicks or unclicks the NA button.

Please see screen recording below for reference on this scenario.




https://github.com/nerubia/kh360-nodejs/assets/1640285/838803da-4d3e-495a-943f-7594f8884380



https://github.com/nerubia/kh360-nodejs/assets/1640285/942c0e83-0de2-4c3e-b0f0-e7ab1d95ba7e

**Comment by sheilaramas** [comment]
OK verified

**Comment by sheilaramas** [comment]
OK verified
