### ISSUE TITLE
Evaluation Form - if all answers are N/A, set weight to 0.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#174]
**DESCRIPITON**

- If all answers are N/A, add the following steps when computing for the score:
         - set the weight to 0 instead of computing based on percentage involvement and duration of assignment

**Comment by emmaacha** [comment]
PR: [#198](https://github.com/nerubia/kh360-nodejs/pull/198)

**Comment by sheilaramas** [comment]
OK verified

**Comment by sheilaramas** [comment]
There is an issue that is a bit related to this ticket.
This ticket is for updating evaluation.weight = 0 if all answers in the form were marked as NA.

However, the weight in evaluation_result_details was also updated to 0 which should not be the case.
This also resulted to a 0 overall score in evaluation_results table. Please see DB screenshot below.

<img width="1283" alt="image" src="https://github.com/nerubia/kh360-nodejs/assets/1640285/0c54310f-6da9-411c-b1de-a4e4c3c6d03c">


Expected:
- [ ] Weight in evaluation_result_detail should not be 0.

**Comment by emmaacha** [comment]
PR: [#215](https://github.com/nerubia/kh360-nodejs/pull/215)

**Comment by sheilaramas** [comment]
OK VERIFIED
