### ISSUE TITLE
Delete External Evaluator - when deleting external evaluator, perform soft delete if external evaluator has related evaluations

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#177]
**DESCRIPTION**

- [x] When deleting external evaluators, please check first if this evaluator has related evaluations
- [x] Perform soft delete if related evaluation statuses are either 
          - Pending
          - Open
          - Ongoing
          - Submitted
          - Reviewed

- [x] Perform hard delete if no related evaluations
- [x] If there are related evaluation and statuses are either Draft, Excluded, Cancelled, Expired, perform the following:
          - hard delete
          - delete all related evaluations and evaluation_ratings

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/181

**Comment by sheilaramas** [comment]
OK verified

**Comment by sheilaramas** [comment]
**UPDATES**

- [ ] If there are related evaluation and statuses are either **For Removal** and **Removed**, perform the following:
          - hard delete
          - delete all related evaluations and evaluation_ratings

* So for the following statuses, evaluation and evaluation_ratings records must be deleted: Draft, Excluded, Cancelled, Expired, For Removal, Removed

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/305

**Comment by sheilaramas** [comment]
ok verified
