### ISSUE TITLE
My Evaluations - create API to retrieve data for My Evaluation screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#195]
**DESCRIPTION**

- [x] Create API to retrieve all evaluation_administrations the user is evaluee of
- [x] Only include records of evaluation administration whose status is closed
- [x] Also retrieve the banding result of the evaluee

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/199

**Comment by sheilaramas** [comment]
**CHANGES**

- [ ] Please change to include records of evaluation administrations whose status is `Published` and instead of `Closed`.

- [ ]

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/266

**Comment by sheilaramas** [comment]
OK verified.
