### ISSUE TITLE
Email Reminder Enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#201]
### **DESCRIPTION**

Can you please implement the following enhancements?

- [x] Possible to indent the list of pending evaluations?
- [x] For the list, can you include the following:
          - What type of evaluation? (display name of the template)
          - For what project (if this applies... e.g. if HR Evaluation, then no need to display project)

- [x] If there are 2 or more records with the same template and project, include the duration. Example:
          - Ardiente, Niño Allen (PM Evaluation for iAssess from June 3 - July 31, 2023)
          - Ardiente, Niño Allen (PM Evaluation for iAssess from October 1 - October 31, 2023)
          - Ardiente, Niño Allen (PM Evaluation for ProductHQ)

- [x] Can you remove extra line spacing between Best Regards and KH360 (please update the migration for this)

**This is the email I received:**

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/d64d4a83-cfb0-4675-b98c-84186189d99a)

**Sample Email (with suggested enhancements):**

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/349702fb-c4f6-48ce-81b8-eb232dc58b5f)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/203

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/211

**Comment by sheilaramas** [comment]
@jatnerubia  was this implemented?

` Additional Enhancement - can we also change the order to show earliest first? Like in the case above, the 2nd line for January 1- Oct 15 should be displayed first before the October 16 - Dec 31 duration)`

**Comment by jatnerubia** [comment]
![Image](https://github.com/nerubia/kh360-nodejs/assets/146687629/fc50d119-356b-4c4b-8272-fb3b587cc93b)

@sheilaramas Yes, it's sorted by last name, first name, project name, and start date.
Please don't mind the end date; I already have a pull request for that.

**Comment by sheilaramas** [comment]
OK verified.
