### ISSUE TITLE
Create Seeder for HR Notification for Request for Removal

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#206]
**DESCRIPTION**

- Create seeder for HR notification for Request for Removal
- This will be the email that will be sent to KH360 Admin to notify them of the evaluator request.
- Contents as follows:

- [ ] name: `Request to Remove Evaluation`
- [ ] template_type: `Request to Remove Evaluation`
- [ ] is_default: 1
- [ ] Email Subject: `Request to Remove Evaluation`
- [ ] Content:

```
Dear KH360 Admin,

I would like to request to remove {{evaluee_first_name}} {{evaluee_last_name}} with details below from my list of evaluees:
Evaluation Type: {{template_display_name}}
{{project name information}}
{{project duration information}}

Comments: {{comments}}

Click on this {{link}} to approve or reject this request.


Thanks and Best Regards,
KH360 Team on behalf of {{evaluator first name}} {{evaluator_last_name}} 
```

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/229

**Comment by sheilaramas** [comment]
OK verified
