### ISSUE TITLE
Create seeder for No Available Evaluation Results template

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#208]
**DESCRIPTION**

- [ ] Create seeder for message to be displayed in My Evaluations if there are no available evaluation results yet
- [ ] Details as follows:

          - Type = `No Available Evaluation Results`
          - is_default = 1
          - Subject: blank
          - Content:

```
Uh-oh! 🤷‍♂️

Looks like our magical elves are still working their charm behind the scenes, and your results haven't arrived just yet. Don't worry, though – good things come to those who wait!

In the meantime, why not grab a cup of coffee or practice your superhero pose? 🦸‍♀️ We'll have those results ready for you in no time.

Stay tuned and keep the positive vibes flowing! ✨
```

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/213
