### ISSUE TITLE
Create Performance Evaluation Step 4 - Query Evaluation Templates that are applicable for the Employee

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#21]
**DESCRIPTION**
This API will be called every time employee is clicked from Step 3. This will be used to retrieve the data that will be displayed in the Left Panel.

1. Select all distinct evaluation templates that are applicable for the employee.
2. Sample query below:

```

select * from evaluation_templates where id in
(select distinct evaluation_template_id from evaluations where evaluation_result_id = 32);

```

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/dd36edcf-d5e9-4a7e-a865-e52fa50839de)

3. Based on sample results above, there are 4 different templates that are applicable. So there will be 4 rows on the left panel.
4. Use the `display_name` field as label for each row.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/37
