### ISSUE TITLE
Generation of Evaluation Records - setting of start and end date

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#210]
**DESCRIPTION**

This ticket is an enhancement to ->
[Create API for generating all evaluation records for employees included in the Performance Evaluation. This will be called once the ADMIN will click on SAVE AND PROCEED in Step 2B.#23](https://github.com/nerubia/kh360-nodejs/issues/23)

- During generation of evaluation records, originally, eval_start_date and eval_end_date were set to as follows:
          - eval_start_date: B's project_member.start_date (2023-10-16)
          - eval_end_date: B's project_member.end_date (2023-12-31)

- There should be an additional condition to be set here. 

- [x] For `eval_start_date`, first check if `project_member.start_date` is lesser than `evaluation_administration.eval_period_start_date`. 
          - If it is lesser, then set `eval_start_date = evaluation_administration.eval_period_start_date`
          - If not, then set `eval_start_date = project_member.start_date`

- [x] For `eval_end_date`, first check if `project_member.end_date` is greater than `evaluation_administration.eval_period_end_date`. 
          - If it is greater, then set `eval_end_date = evaluation_administration.eval_period_end_date`
          - If not, then set `eval_end_date = project_member.end_date`

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/212

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- [ ] Wrong evaluation end date set for end date.  Please see DB screenshot below. The last 3 columns show related records from project_members table for reference on the actual end dates.


![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/eee656ae-fda6-48ca-bca4-6eb43c58755b)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/222

**Comment by sheilaramas** [comment]
OK verified

**Comment by sheilaramas** [comment]
Reopening this ticket. Start and End dates for External Evaluators are wrong. Please see screenshot below. 

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/85469cd4-fbe1-4df2-8935-0a6d4d30d9f4)

It should follow the same logic as internal evaluators.

**Comment by sheilaramas** [comment]
ok verified
