### ISSUE TITLE
Generating Evaluations if evaluator_role is 1

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#220]
**DESCRIPTION**

- [x] This ticket is an enhancement to [Create API for generating all evaluation records for employees included in the Performance Evaluation. This will be called once the ADMIN will click on SAVE AND PROCEED in Step 2B.#23](https://github.com/nerubia/kh360-nodejs/issues/23)

- [x] For templates whose evaluator_role = 1, please add the following extra steps:

1. Get all users whose user_detail.user_type = `bod`
2. Insert evaluation for each of these users (1 evaluation record per user)
3. Follow the other steps

- [x] The difference here is just that instead of searching for evaluators with the same project in project members table, you just need to base it on users who are BODs in their user type.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/231
