### ISSUE TITLE
Create API for Request to Remove function

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#223]
**DESCRPTION**

- This API will be called when the evaluator will click on the `Request to Remove` button in Evaluation Form
- When this API is called, do the following:

- [x] Set evaluation.status = `For Removal`
- [x] For email recipient, retrieve all records from email_recipients where email_type = `KH360 Admin`. Please note, there can be multiple records that will be returned. So please be sure to send to all of these emails. 
- [x] For email content, please refer to email_templates and use type = `Request to Remove Evaluation` and default = 1 

**EMAIL CONTENT**

- The content of emails is shown below:

```
Dear KH360 Admin,

I would like to request to remove {{evaluee_first_name}} {{evaluee_last_name}} with details below from my list of evaluees:
Evaluation Type: {{template_display_name}}
{{project name information}}
{{project duration information}}

Comments: {{comments}}

Click on this {{link}} to approve or reject this request.


Thanks and Best Regards,
KH360 Team on behalf of {{evaluator first name}} {{evaluator_last_name}} 
```

- Some additional notes for the placeholders:
- [x] For {{project name information}} and {{project duration information}}, this will only be displayed if there is an associated project_member_id. If there is none, remove this placeholder.
- [x] {{project name information}}, replace with `Project Name: {{project_name}}`
- [x] {{project duration information}}, replace with `Project Duration: {{project_duration}}`
- [x] Date format should be as follows:
          - for same month and year: mmm dd - dd, yyyy
          - for same year: mmm dd - mmm dd, yyyy
          - for different year: mmm dd, yyyy - mmm dd, yyyy

- [x] {{link}} -> use link but clickable and would open the Evaluation Progress Screen of the Evaluation Administration Record of that request
- [x] If the admin is currently logged in, this page should be loaded
- [x] If admin is not logged in, show login page, and redirect to this page after login

**Comment by emmaacha** [comment]
#234
