### ISSUE TITLE
Create API to Approve or Decline Request to Remove Evaluation from Evaluator

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#224]
### **DESCRIPTION**

- Create API for approving or rejecting request to remove evaluatee
- This API will be called from Eval Admin Progress Screen when the admin will click on either Approve or Reject

**For Approve, do the following:**

- [x] Set evaluation.status = `Removed`
- [x] If there are evaluation ratings that were saved, clear these back and set to 0 (similar to newly added evaluation results records where rate and score are 0, and answer_option_id is null.
- [x] If the evaluator inputted  some ratings / or NA with comments, these should be cleared as well.
- [x] Send email to the evaluator. Use email_template with type = `Approved Request to Remove Evaluee` and is_default = 1
- [x] Once approved, this evaluation should no longer be displayed in the list of evaluations for the Evaluator (so please double check that evaluations with `Removed` status are not displayed there. :)

**For Declined, do the following:**
- [x] Set evaluation.status = `Ongoing`
- [x] Send email to the evaluator. Use email_template with type = `Declined Request to Remove Evaluee` and is_default = 1

### **APPROVED EMAIL CONTENT / PLACEHOLDERS**

- This is the default email content below:

```
Hi {{evaluator_first_name}},

Hope this note adds a little sunshine to your day! 🌞 Just wanted to drop you a quick line to say your request to remove your {{template_display_name}} of {{evaluee_first_name}}  {{evaluee_last_name}} {{project_details}} has been given the green light and is now removed from your list. 

If you have any further questions or if there is anything else we can assist you with, please feel free to reach out. Your cooperation in this matter is highly valued, and we want to ensure that the evaluation process is as effective and meaningful as possible.

Thanks for making the workplace vibe even better!

Cheers,
KH360 Team
```

- For {{project_details}} placeholder, please do the following:

- [x] if evaluation has no related project_member_id, then this will be replaced with '' (blank)
- [x] if there is an associated project_member_id, replace with as follows:
          - for {{project_name}} during {{project_duration}}
- [x] {{project_duration}}, date format should be as follows:
- [x] Date format should be as follows:
          - for same month and year: mmm dd - dd, yyyy
          - for same year: mmm dd - mmm dd, yyyy
          - for different year: mmm dd, yyyy - mmm dd, yyyy

### **DECLINED EMAIL CONTENT / PLACEHOLDERS**

- This is the default email content below:

```
Hi {{evaluator_first_name}},

Hope you're doing well. Quick update on your request to remove your {{template_display_name}} of {{evaluee_first_name}}  {{evaluee_last_name}} {{project_details}} from your list: after giving it a thorough look, we're unable to proceed with the removal at this time.

We totally get that evaluations are a bit like trying to fit a square peg in a round hole sometimes, but in this case, we still think your inputs on {{evaluee_first_name}}'s performance is very important. If there's any way we can make it more efficient or if you have further concerns, please let us know so we can assist you.

Thanks for your understanding, and let's keep the lines of communication open!

Best Regards,
KH360 Admin
```

- For {{project_details}} placeholder, please do same as approval email

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/233

**Comment by sheilaramas** [comment]
OK verified
