### ISSUE TITLE
Create seeder for Approved Request to Remove Evaluation email content

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#226]
**DESCRIPTION**

- Please create seeder for Email Contents for Approved Requests to Remove Evaluation
- This will be sent to the evaluator once his/her request to remove the evaluee is approved
- Please set the following data in the DB:

- [x] name: Approved Request to Remove Evaluee
- [x] template_type: Approved Request to Remove Evaluee
- [x] is_default: 1
- [x] subject: Approved Request to Remove {{template_name}} of {{evaluee_first_name}} {{evaluee_last_name}}
- [x] content:

```
Hi {{evaluator_first_name}},

Hope this note adds a little sunshine to your day! 🌞 Just wanted to drop you a quick line to say your request to remove your {{template_display_name}} of {{evaluee_first_name}}  {{evaluee_last_name}} {{project_details}} has been given the green light and is now removed from your list. 

If you have any further questions or if there is anything else we can assist you with, please feel free to reach out. Your cooperation in this matter is highly valued, and we want to ensure that the evaluation process is as effective and meaningful as possible.

Thanks for making the workplace vibe even better!

Cheers,
KH360 Team

``

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/232

**Comment by sheilaramas** [comment]
OK Verified
