### ISSUE TITLE
Create seeder for KH360 Admin email recipient

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#227]
**DESCRIPTION**

- Create seeder to insert new records in email_recipients table
- This will be the email recipients who will receive the Request to Remove email
- Please add with the following details:

- [x] email_type: `KH360 Admin`
- [x] email: `kh360admin@nerubia.com`
- [x] status: 1

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/229

**Comment by sheilaramas** [comment]
OK verified
