### ISSUE TITLE
Create API for generating all evaluation records for employees included in the Performance Evaluation. This will be called once the ADMIN will click on SAVE AND PROCEED in Step 2B.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#23]
**Description**

1. Get all projects that the employee has been involved in within the evaluation period. You can get this from `project_members` table (filter by user_id, start_date and end_date)
2. Loop through each project assignment. 
          a. get the role of the employee for that project assignment
          b. based on the role, look up all the applicable templates for that role (`select * from evaluation_templates where evaluee_role_id = project_member.project_role_id`)
                    - Example, for PM role, applicable template would be:
                              - PM Evaluation by BOD (evaluator = BOD)
                              - PM Evaluation by DEV (evaluator = DEV)
                              - PM Evaluation by QA (evaluator = QA)

3. Get who are the evaluators for these templates
4. Search the projects who are assigned under these roles during the evaluation period
5. Insert a record under `evaluations` for these evaluators

**Comment by sheilaramas** [comment]
**SAMPLE QUERY**


```

SET @USER_ID = 20049;
SET @PERIOD_START_DATE = '2023-01-01';
SET @PERIOD_END_DATE = '2023-12-31';

select distinct pm2.project_id, pm2.project_role_id , pm2.user_id
from project_members pm2
left join projects p on p.id = pm2.project_id
left join users u on u.id = pm2.user_id
left join project_roles pr on pr.id = pm2.project_role_id
	where 
	pm2.user_id != @USER_ID and 
	pm2.project_role_id in 
     
     -- this part gets the evaluator role ID's applicable for the user
     (select evaluator_role_id from evaluation_templates where evaluee_role_id in 
          
          -- this part selects the roles of the user in all projects assigned to him within the evaluation period
          (select pm.project_role_id from project_members pm where user_id = @USER_ID and 
          (( pm.start_date between @PERIOD_START_DATE and @PERIOD_END_DATE) OR ( pm.end_date between @PERIOD_START_DATE and @PERIOD_END_DATE))))
    
    and project_id in 
    	(select distinct pm.project_id from project_members pm where pm.user_id = @USER_ID and 
          (( pm.start_date between @PERIOD_START_DATE and @PERIOD_END_DATE) OR ( pm.end_date between @PERIOD_START_DATE and @PERIOD_END_DATE)))
    
    and
		(( pm2.start_date between @PERIOD_START_DATE and @PERIOD_END_DATE) OR ( pm2.end_date between @PERIOD_START_DATE and @PERIOD_END_DATE))


group by pm2.user_id, pm2.project_id, pm2.project_role_id
order by pm2.project_id, pm2.project_role_id, pm2.user_id;
```

**Comment by sheilaramas** [comment]
**ALTERNATIVE SOLUTION**

A. Get all project_member records for the user within the evaluation period.

```
SET @USER_ID = 20049;
SET @PERIOD_START_DATE = '2023-01-01';
SET @PERIOD_END_DATE = '2023-12-31';

select * from project_members
where 
user_id = @USER_ID and 
(( start_date between @PERIOD_START_DATE and @PERIOD_END_DATE) OR ( end_date between @PERIOD_START_DATE and @PERIOD_END_DATE));

```

B. The results here will be the one displayed on the left panel (1 row per record).

C. Loop through each project_member record.

C.1.

**Comment by sheilaramas** [comment]
C.4. Retrieve all HR evaluators and insert evaluation records for each HR. To retrieve hr evaluators:
`select user_id from user_roles where name = 'khv2_hr_evaluators';`

C.4.1. Loop through each user_id retrieved.

C.4.2. Insert evaluation records as follows:

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/38

**Comment by sheilaramas** [comment]
**ISSUE**

- [ ] In the case below, there should only be 1 record inserted for Racquel Rosel for iAssess project. 


![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/44571e4f-b9e7-4bc9-865d-ef1def76af14)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/88

**Comment by sheilaramas** [comment]
**ADDITIONAL COMMENT**

- [ ] Right now, there is only 1 template applicable for HR Roles. In the future, there might be more than 1 template. So the code must be adjusted to accommodate multiple templates per role.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/94

**Comment by sheilaramas** [comment]
Will create separate ticket for verification.

**Comment by sheilaramas** [comment]
### **CORRECTIONS WITH SQL QUERY**

- There is a bug with the query used
- If the filter interval is within the project duration interval, then project_member record wont be returned.
- Please correct as follows:


- [ ] Getting project member records within the evaluation period

**OLD:**

B. Get all project_member records for the employee within the evaluation period.

SET @USER_ID = 20049;
SET @PERIOD_START_DATE = '2023-01-01';
SET @PERIOD_END_DATE = '2023-12-31';

select * from project_members
where 
user_id = @USER_ID and 
(( start_date between @PERIOD_START_DATE and @PERIOD_END_DATE) OR ( end_date between @PERIOD_START_DATE and @PERIOD_END_DATE));



**NEW:**

B. Get all project_member records for the employee within the evaluation period.

SET @USER_ID = 20049;
SET @PERIOD_START_DATE = '2023-01-01';
SET @PERIOD_END_DATE = '2023-12-31';

select * from project_members
where 
user_id = @USER_ID and 
(( pm.start_date between @PERIOD_START_DATE and @PERIOD_END_DATE) OR ( pm.end_date between @PERIOD_START_DATE and @PERIOD_END_DATE)
OR
( @PERIOD_START_DATE between pm.start_date  and pm.end_date) OR ( @PERIOD_END_DATE between  pm.start_date  and pm.end_date));
