### ISSUE TITLE
Create seeder for Declined Request to Remove Evaluation email content

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#230]
**DESCRIPTION**

- Please create seeder for Email Contents for Declined Requests to Remove Evaluation
- This will be sent to the evaluator once his/her request to remove the evaluee is declined
- Please set the following data in the DB:

- [x] name: Declined Request to Remove Evaluee
- [x] template_type: Declined Request to Remove Evaluee
- [x] is_default: 1
- [x] subject: Declined Request to Remove {{template_name}} of {{evaluee_first_name}} {{evaluee_last_name}}
- [x] content:

```
Hi {{evaluator_first_name}},

Hope you're doing well. Quick update on your request to remove your {{template_display_name}} of {{evaluee_first_name}}  {{evaluee_last_name}} {{project_details}} from your list: after giving it a thorough look, we're unable to proceed with the removal at this time.

We totally get that evaluations are a bit like trying to fit a square peg in a round hole sometimes, but in this case, we still think your inputs on {{evaluee_first_name}}'s performance is very important. If there's any way we can make it more efficient or if you have further concerns, please let us know so we can assist you.

Thanks for your understanding, and let's keep the lines of communication open!

Best Regards,
KH360 Admin

``

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/232

**Comment by sheilaramas** [comment]
OK verified
