### ISSUE TITLE
Create Seeder for changes related to Evaluator Recommendation

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#236]
**DESCRIPTION**

- Create a seeder to set initial values of `with_recommendations` field in `evaluation_templates` table
- Please set the `with_recommendations` of the following records to 1

- [x] id = 1 (PM Evaluation by BOD)
- [x] id = 4 (DEV Evaluation by PM)
- [x] id = 6 (DEV Evaluation by Code Reviewer)
- [x] id = 8 (QA Evaluation by PM)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/238

**Comment by sheilaramas** [comment]
OK verified
