### ISSUE TITLE
Create DB migration to add necessary fields in evaluations table

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#24]
**Description**

Need to add the following fields:

- [ ] project_member_id (FK for project_members table, after project_id)
- [ ] for_evaluation (boolean, default false, after project_member_id)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/29

**Comment by sheilaramas** [comment]
Please change order as specified above, should be after project_id

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/64

**Comment by sheilaramas** [comment]
@jatnerubia  please update Beta DB.

**Comment by jatnerubia** [comment]
@sheilaramas done ^^
