### ISSUE TITLE
Create API to set evaluation administration status to Published

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#242]
### DESCRIPTION

- This API will be called from View Evaluation Administration Screen (and possible from other screens in the future) to set status to Published.
- Once published, evaluation results can now be viewed by the evaluees
- Please do the following:
          - [ ] Set status of evaluation_administration to `Published`
          - [x] Send email to all evaluees (only 1 email should be received by the evaluee)
          - [ ] Content of email will be based on email_template.template_type = `Publish Evaluation Results` and is_default = 1

**Other Validations**

- [x] evaluation administration records can only be set to `Published` if current status is `Closed`. 

**Sample Email Content**

```
Hi {{evaluator_first_name}},

I hope this message finds you well. We wanted to inform you that the results of your recent performance evaluation are now available for your review.

To access your evaluation, please click on this {{link}} or you can log in to KH360 and navigate to the "My Evaluations" section.

We encourage you to take the time to carefully review the feedback provided. This is an opportunity to reflect on your accomplishments and areas for improvement, and to discuss any questions or concerns you may have with your Career Manager during your upcoming performance review meeting.

If you encounter any technical difficulties or have questions regarding the content of your evaluation, please don't hesitate to reach out to our HR department at hr@nerubia.com.

Thank you for your hard work and dedication to the company. We value your contributions and look forward to supporting your continued success.

Cheers,
KH360 Team
```

**Special Placeholders**

- [ ] Only the text `link` should be displayed but is hyperlinked to the Evaluation Results screen (for that specific evaluation).
- [ ] So when clicked, and if currently logged in, should redirect directly to the screen below, so use the link to the screen below.
- [ ] If not logged, display login screen and once logged, redirect to this screen immediately

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/3c5306db-4ba0-47a1-9a8c-42607fec5ae4)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/249
