### ISSUE TITLE
Enhancements for Evaluation Notification Email

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#259]
**DESCRIPTION**

- Please make changes to the email below. Current as follows:

```

Dear Evaluator,

Good day!

As part of our commitment to professional development and fostering a culture of feedback, we are reaching out to request for you to evaluate the performance your respective colleagues during this period: January 1, 2023 to November 30, 2023.

Please click this https://kh360-beta.kaishahero.com/evaluation-administrations/1/evaluations/all to access 2023 Year End Evaluation.

Feel free to add any additional comments or insights you believe are relevant. Your insights are invaluable in providing an understanding of each persons's contributions and areas for growth to help enhance their performance and contribute effectively to the overall success of the team.

The deadline for completing these evaluations is on Sunday, December 31, 2023. If you encounter any technical issues or have questions regarding the process, please feel free to reach out to any of the HR team members at [hr@nerubia.com](mailto:hr@nerubia.com).

Thank you for your dedication to fostering a culture of continuous improvement within our company.

```

- Please make the following changes:

- [x] Change the url link, instead of showing entire URL, change to `link` and hyperlink to the page.
- [x] Add Salutation (please make seeder for this)

Updated Sample below with the changes:

====================

Dear Evaluator,

Good day!

As part of our commitment to professional development and fostering a culture of feedback, we are reaching out to request for you to evaluate the performance your respective colleagues during this period: January 1, 2023 to November 30, 2023.

Please click this [link](https://kh360-beta.kaishahero.com/evaluation-administrations/1/evaluations/all) to access 2023 Year End Evaluation.

Feel free to add any additional comments or insights you believe are relevant. Your insights are invaluable in providing an understanding of each persons's contributions and areas for growth to help enhance their performance and contribute effectively to the overall success of the team.

The deadline for completing these evaluations is on Sunday, December 31, 2023. If you encounter any technical issues or have questions regarding the process, please feel free to reach out to any of the HR team members at [hr@nerubia.com](mailto:hr@nerubia.com).

Thank you for your dedication to fostering a culture of continuous improvement within our company.

Best Regards,
KH360 Team

====================

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/261

**Comment by sheilaramas** [comment]
Please implement for external evaluators also.
This is what I received as external evaluator.



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/b0f17d6d-a676-43d4-ae71-32b6ace78fea)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/267

**Comment by sheilaramas** [comment]
OK verified
