### ISSUE TITLE
Add Evaluator - create API to retrieve data needed for Add Evaluator Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#263]
**DESCRIPTION**

Make the following API's

- [x] retrieve the list of evaluator names (like search)
- [x] retrieve the list of active templates
- [x] retrieve the list of applicable projects (or use the one for adding external evaluators)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/270

**Comment by sheilaramas** [comment]
OK Verified.
Additional note... currently, evaluee's name appears in the list of options. We will just allow this (for special cases wherein we need the evaluee to evaluate herself)
