### ISSUE TITLE
Add Evaluator - create API to save newly added evaluator

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#264]
**DESCRIPTION**

- Make an API to save new evaluator (added manually)
- This will be called when ADD button is clicked in Add Evaluator screen
- Save the following data in `evaluations` table:

- [x] evaluation_template_id: based on what is selected
- [x] evaluation_administration_id: current eval admin id
- [x] evaluation_result_id: based on current evaluation_result
- [x] evaluator_id: user id of evaluator selected in the screen
- [x] evaluee_id: current evaluee
- [x] project_id: selected from the screen (can be null)
- [x] project_member_id: selected from the screen (can be null)
- [x] for_evaluation: 1
- [x] eval_start_date: same logic with creating evaluations
- [x] eval_end_date: same logic with creating evaluations
- [x] percent_involvement: based on the project_member record selected
- [x] status: based on evaluations logic

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/272

**Comment by sheilaramas** [comment]
Verified for the rest. Still need to verify the following:

- [ ] End dates (if schedule duration is different from project dates)
