### ISSUE TITLE
Create API for Generating Evaluations

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#27]
**DESCRIPTION**

**Evaluation Administrations**

- [x] Check current date. 
            - If it is within the evaluation_schedule, then update `evaluation_administration.status = 'Ongoing'`
            - If it is before the evaluation_schedule, then update `evaluation_administration.status = 'Pending'`

**Evaluation Results**
- [x] Loop through each `evaluation_results` record
- [x] For each `evaluation` record that are checked related to the `evaluation_result`, update evaluation.status
            - If current date is within the evaluation_schedule, `evaluation.status = 'Open'`
            - If current date is before the evaluation_schedule, `evaluation.status = 'Pending'`
- [x] Generate the associated `evaluation_rating` records for these evaluations

### **Evaluations**
- [ ] Loop through each evaluations record
- [x] Get all evaluations where `evaluation.status = 'Draft'`
- [x] Update the status of these records to as follows:
            - If it is within the evaluation_schedule, `evaluation.status = 'Open'`
            - If it is before the evaluation_schedule, update `evaluation.status = 'Pending'`

- For reference, these are the evaluation statuses:
                      - `Draft`: This is the initial status of the evaluation form. At this stage, Admin is still in the process of generating the forms.
                      - `Excluded`: Not part of the evaluation. These are the unchecked items in Step 4.
                      - `Pending`: Evaluation form is ready, but evaluation schedule has not yet started
                      - `Open`: Evaluation period has started but evaluator has not yet started evaluation (evaluator has not yet opened and filled up the form)
                      - `Ongoing`: Evaluator has filled up the form but has not yet submitted the form 
                      - `Submitted`: Evaluator has completed the form and has submitted his/her ratings for computation
                      - `Reviewed`: This means that the results are already computed and collated

### **Evaluation Ratings**

- [x] Based on the evaluation template, loop through each evaluation_template_content and use the data here to insert records under `evaluation_ratings`.
- [x] Let's use evaluation_template_id = 5 as an example.

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/e6eea0be-d44d-4aff-96a6-935b06bb1e54)

- [x] This is the related content for this template.

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/b1e2792d-b7b0-4c0a-905c-c4079f002397)

- [x] So for each record here, insert an equivalent evaluation_results record. Let's use id = 27 above as an example:

- evaluation_administration_id: based on evaluation_administration_id
- evaluation_id: based on evaluation_id
- evaluation_template_id: 2
- evaluation_template_content_id: 27
- answer_option_id: null
- rate: null
- percentage: 22 (get this from evaluation_template_contents.rate)
- score: null
- created_at: date today
- updated_at: date today

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/48

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] When retrieving applicable evaluation_template_contents, please include the is_active = 1 as part of the filter.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/97

**Comment by sheilaramas** [comment]
OK verified
