### ISSUE TITLE
Create seeder for Evaluation Complete Email

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#276]
**DESCRIPTION**

- Create seeder for Evaluation Complete Thank You Email
- This will be the email that will be sent to KH360 Admin to notify them of the evaluator request.
- Contents as follows:

- [x] name: `Evaluation Completed by Evaluator`
- [x] template_type: `Evaluation Completed by Evaluator`
- [x] is_default: 1
- [x] Email Subject: `Evaluation Completed by {{evaluator_last_name}}, {{evaluator_first_name}}`
- [x] Content:

```
Dear KH360 Admin,

Please be informed that {{evaluator_last_name}}, {{evaluator_first_name}} has successfully completed the Evaluation Forms for {{evaluation_administration_name}} on {{submitted_date}}.

The completed evaluation forms are now available for your review. Kindly access the system to view and analyze the data at your convenience.

Thanks and Best Regards,
KH360 Team
```

**Comment by emmaacha** [comment]
PR: [#277](https://github.com/nerubia/kh360-nodejs/pull/277)

**Comment by sheilaramas** [comment]
ok verified in DB
