### ISSUE TITLE
Closing Evaluation Computation for ZScores - please set to 0 zscores for all evaluations whose status is not Submitted

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#279]
**DESCRIPTION**

- [x] When computing for zscores (called when closing evaluation_administration), for those evaluations that are `Expired` or `Removed`, please set zscores to 0 automatically.
- [x] Only compute zscores for status = `Submitted`

This is how the current data looks like:

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/226faec0-0674-452f-abce-1c2b9f8cbb19)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/282

**Comment by sheilaramas** [comment]
**ISSUE**

- [ ] It is no longer computing for zscores. It should still compute for zscores if status is submitted.
