### ISSUE TITLE
Create Seeder for [Evaluation Complete Thank You Message External] Email Template

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#290]
**DESCRIPTION**

- [x] Create seeder for message to be displayed when an external evaluator completes their evaluation forms.
- [x] Set template_type = Evaluation Complete Thank You Message External
- [x] All the other data, please follow template_type = Evaluation Complete Thank You Message

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/291

**Comment by sheilaramas** [comment]
ok verified
