### ISSUE TITLE
Adding External Evaluators - allow adding external evaluator with the same email as soft-deleted external evaluator

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#294]
**DESCRIPTION**

- Currently, you cannot add an external evaluator with the same email address as a previously deleted one (soft delete)
- When checking for uniqueness for the email, you should exclude in the condition those that are soft deleted
- Similarly, when logging in, make sure to use the record that is not deleted (if there are duplicate emails that exist where one is soft-deleted and the 2nd one is active)

**Comment by emmaacha** [comment]
#301

**Comment by sheilaramas** [comment]
OK verified
