### ISSUE TITLE
Duplicate record inserted in evaluation_result_details when adding external evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#299]
**DESCRIPTION**

- [x] Duplicate record inserted in evaluation_result_details when adding external evaluators

https://github.com/nerubia/kh360-nodejs/assets/1640285/906d85f1-0a62-4e27-993f-e02ade0e5bdd

**Comment by emmaacha** [comment]
PR: #303

**Comment by sheilaramas** [comment]
OK verified
