### ISSUE TITLE
Create database migration for Email Templates

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#3]
**Description**

Table must have the following fields:

- [ ] id
- [ ] name
- [ ] template_type
- [ ] is_default
- [ ] subject
- [ ] content
- [ ] created_by_id
- [ ] updated_by_id
- [ ] created_at
- [ ] updated_at

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/18
