### ISSUE TITLE
Approve Remove Evaluation - check if 100% complete

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#311]
**DESCRIPTION**

- Scenario: Evaluator has completed his evaluations except for those that he requested for Removal. So once the admin has approved all, progress is 100% but no email will be sent out to KH360 Admin since this routine is only done in Evaluation Form (if evaluator completed). 
- Change: Please add checking in Removal Approval to check if all evaluations are completed (all are either submitted or removed). If yes, send the email notification to Admin that evaluator has completed the evaluation.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/313

**Comment by sheilaramas** [comment]
**ADDITIONAL CHANGE**

- Please add the following changes:

- [ ] If all evaluations are completed, aside from sending an email notification to Admin, also send an email notification to the evaluator.
- [ ] The email for to evaluator should only be sent for this scenario,  (because the evaluator is not able to see the thank you message in the screen since the completion was processed in the backend)
- [ ] For content of email, please base it on template_type = `Evaluation Complete Thank You Message`

- [ ] Can you manually add this in the email? This is just temporary, will create a final fix for this in a separate ticket (to be done in the future)
```

Thanks and Best Regards,
KH360 Admin```

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/330

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/336

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- Additional Change: for template type, please check the type of evaluator.

- [ ] If evaluator is external, use template_type = `Evaluation Complete Thank You Message External`
- [ ] If evaluator is internal, use template_type = `Evaluation Complete Thank You Message`

**Comment by jatnerubia** [comment]
@sheilaramas done ^^
