### ISSUE TITLE
Create API for Project Assignments (CRUD)

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#314]
**DESCRIPTION**

- Create API for the following:

- [ ] Adding new project assignment (add new record to project_members table)
- [ ] Updating project assignment
- [ ] Deleting project assignment
- [ ] Viewing project assignment

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/316

**Comment by sheilaramas** [comment]
Moving this for Live release. Separate tickets to be created once this is tested with the FE.

**Comment by sheilaramas** [comment]
Closing this ticket, testing will be done via the FE (separate ticket to be created)
