### ISSUE TITLE
Create Migration and Seeder for changes to project_roles table

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#315]
### **Description**

**- Create migration for the following fields:**
- [x] for_project (boolean, between `is_evaluee` and `created_at`)

**- Create seeder and set the value of `for_project` for the following roles:**
- [x] Project Manager
- [x] System Analyst
- [x] Developer
- [x] Quality Assurance
- [x] Code Reviewer

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/317

**Comment by sheilaramas** [comment]
OK verified in Beta
