### ISSUE TITLE
Create migration and seeder to for ratings table (new table)

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#322]
### **Description**

**- Create migration for new table `score_ratings` with the following fields:**
- [x] id (PK)
- [x] name
- [x] display_name
- [x] min_score
- [x] max_score
- [x] description
- [x] status (boolean)

**- Create migration to add score_ratings_id in evaluation_results table.**
- [x] FK to score_ratings table
- [x] place this between score and zscore

**- Create seeder to populate `score_ratings` table**
- [ ] refer to this [sheet](https://docs.google.com/spreadsheets/d/1o1Fysn56loca4hLThEK6QinoxrW5CVDxzNAz3wJWXOI/edit?usp=sharing) for content.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/324

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- Rename `description` to `result_description`
- Update the table, add the following fields (after `result_description`):

- [ ] evaluee_description (same type with description)
- [ ] created_at
- [ ] updated_at

- update created_at and updated_at fields based on current date and time (UTC)
- I have also added a column in this [sheet](https://docs.google.com/spreadsheets/d/1o1Fysn56loca4hLThEK6QinoxrW5CVDxzNAz3wJWXOI/edit?usp=sharing) for added content. Please update the seeder (or create a new one) as well.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/332

**Comment by sheilaramas** [comment]
**ISSUES**

- [ ] Please populate `result_description` and `evaluee_description`. Currently these are blank.

**Comment by jatnerubia** [comment]
I've manually updated the data. I will refactor the seeder soon.

**Comment by sheilaramas** [comment]
OK. For verification in LIVE
