### ISSUE TITLE
Create migration for email_logs

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#329]
### **Description**

**- Create migration for new table `email_logs` with the following fields:**
- [ ] id (PK)
- [ ] email_type (varchar 100)
- [ ] user_id
- [ ] email_address
- [ ] sent_at (datetime)
- [ ] subject
- [ ] content
- [ ] notes (default blank)
- [ ] mail_id (from sendgrid)
- [ ] email_status (Pending, Sent, Error)
- [ ] created_at
- [ ] updated_at

**Comment by Dev-Nino** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/334

**Comment by sheilaramas** [comment]
**CHANGES**



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/04c3b9d0-c90a-450c-a4ca-5898bff2c857)


Can you change as follows:

- [ ] email address - set to 255 (same as other email address fields)
- [ ] 
- [ ] email status - set to 20


Is there a significance also why some of the lengths are 191? Like mail_id, email status and email address?

**Comment by Dev-Nino** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/346

**Comment by sheilaramas** [comment]
ok verified
