### ISSUE TITLE
My Evaluation Results - update the API to get additional data needed

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#338]
**DESCRIPTION**

- Update the API for My Evaluation Results to retrieve additional info that are needed
- Please retrieve the following:

- [ ] compute % overall score. %score = evaluation_result.score / 10 * 100%
- [ ] based on the evaluation_result.score_rating_id, get the `display_name` and `evaluee_description` from score_ratings table
- [ ] for each of the records for evaluation_result_details, get the following:
          - evaluation_result_detail.score_rating_id, get the `display_name` and `evaluee_description` from score_ratings table 
          - compute % score. %score = evaluation_result_detail.score /10 * 100%
          - get all criteria from evaluation_template_contents based on related evaluation_template. For each criteria, compute for the average rate from all evaluation_ratings records (evaluation_rating.rate) (do not include those rated as NA when computing for the average). Once you get the average score, compute for %score = ave score / 10 * 100%

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/d24cdab2-92a2-4bf7-86b0-806f653be2c3)

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/c091dfb2-db73-4511-8217-38984134c1c5)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/342

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- Please make corrections with how the percentage is computed per evaluation criteria. It should be (ave rate  / 10) * 100 per criteria. Currently, the following is displayed which seems a bit odd:



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/b9154331-5cc5-47ab-9f70-18c9ce8a023c)

- here, PM Evaluation total is just 14% but each detailed criteria is no lesser than 60% (which doesnt add up)
- Expected result for PM evaluation is as follows:


![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/28f530d6-b280-4e3a-9c71-2147c3389cea)




![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/56c86558-3cd6-445e-b51e-201e0b9c118f)





- please refer to sample query below (just replace `evaluation template id` and `evaluation result id`)
```
select er.evaluation_template_content_id, et.display_name, etc.name,  (avg(er.rate) / 10) * 100 as 'Percentage' 
from evaluation_ratings er
left join evaluations e on e.id = er.evaluation_id
left join evaluation_templates et on et.id = er.evaluation_template_id
left join evaluation_template_contents etc on etc.id = evaluation_template_content_id
where 
e.evaluation_result_id = 96
and e.status = 'Submitted'
and er.evaluation_template_id = 4
and er.percentage != 0
group by er.evaluation_template_content_id, er.evaluation_template_id;
```

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/386

**Comment by sheilaramas** [comment]
ok verified
