### ISSUE TITLE
Create migration to update evaluation_rating_details table for score_ratings

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#339]
### **Description**

**- Create migration to add score_ratings_id in evaluation_result_details table.**
- [x] FK to score_ratings table
- [x] place this between weighted_zscore and banding

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/340

**Comment by sheilaramas** [comment]
ok verified
