### ISSUE TITLE
Create API to retrieve data needed for Distribution Chart

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#355]
**DESCRIPTION**

- Input parameter will be the evaluee_id and evaluation_administration_period
- Return will be all as follows:

1. Select all evaluations for the evaluee for the given evaluation period
2. Select all unique evaluators 
3. Loop through each evaluator and retrieve all the evaluations for the evaluation_period and get the evaluee names, project info, percent_involvement, score, zscore and compute for banding also based on zscore

This is more or less the data we need to show in the Distribution Chart
- so each row will be per unique evaluator
- the zscores for all evaluees the evaluator evaluated will be plotted on the graph beside the evaluator

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/8123e626-3e40-4a73-b5e5-7ebec5e468f9)

**Comment by emmaacha** [comment]
#361

**Comment by emmaacha** [comment]
PR: #369

**Comment by sheilaramas** [comment]
OK verified!
