### ISSUE TITLE
Create API to retrieve Attendance and Punctuality Information for Evaluation Results

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#357]
**DESCRIPTION**

- Create API to retrieve the data from the table below:

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/9ba8192e-8480-4eb8-87aa-24abde6277ba)

- 1 row per month (based on the Evaluation Period)
          - for example, evaluation period is January 1 - Dec 31, 2023, so there will be 12 rows in all... 1 row for each month
          - for example, evaluation period is January 31 to February 28, so there will be 2 rows only, January and February

- 1st Column: Month 
- 2nd Column: Total Working Days
          - compute this based on the total weekdays for the month less holidays that fall on a weekday
          - holidays can be retrieved from holidays table 

- 3rd Column: Days Present
          - compute this based getting all attendance records for the user grouped by att_type
          - Sample query: `select att_type, count(att_type) as 'Count'  from attendances where user_id = 86 and `date` >= '2023 01-01' and `date` <= '2023-01-31' group by att_type;`
          - att_type info as follows:
```
                    - 3: present for the whole day
                    - 2: present during PM only
                    - 1: present during AM only
                    - 0: absent for whole day
```
          - so you can compute for total days present = count(att_type=3) + count(att_type=2) * 0.5 + count(att_type=1) * 0.5

- 4th Column: # of Lates which are within Grace Period
          - compute this based getting all attendance records for the user for the period
          - get the count of all attendance records where `late_flag = "Late (within Grace Period)"`

- 5th Column: # of Lates
          - compute this based getting all attendance records for the user for the period
          - get the count of all attendance records where `late_flag = "Late (Counted)"`

- 6th Column: VL / Bday Leaves
          - get all leaves within the specified period
          - based on the leave_ids, retrieve related leave_breakdowns and compute the sum of duration column
          - Leave Types: VL = 1, Birthday Leave = 5
          - sample query: 

```
select sum(duration) from leave_breakdowns
where leave_id in
	(select id from leaves
	where user_id = 86 
	and leave_type_id in (1,5)
	and status in ('pending','approved', 'taken')
	)
and `leave_date` >= '2023-05-01' and `leave_date` <= '2023-05-31';
```

- 7th Column: SL
          - get all leaves within the specified period
          - based on the leave_ids, retrieve related leave_breakdowns and compute the sum of duration column
          - Leave Types: SL = 2
          - sample query: 

```
select sum(duration) from leave_breakdowns
where leave_id in
	(select id from leaves
	where user_id = 86 
	and leave_type_id = 2
	and status in ('pending','approved', 'taken')
	)
and `leave_date` >= '2023-05-01' and `leave_date` <= '2023-05-31';
```

- 8th Column: EL
          - get all leaves within the specified period
          - based on the leave_ids, retrieve related leave_breakdowns and compute the sum of duration column
          - Leave Types: EL = 3
          - sample query: 

```
select sum(duration) from leave_breakdowns
where leave_id in
	(select id from leaves
	where user_id = 86 
	and leave_type_id = 3
	and status in ('pending','approved', 'taken')
	)
and `leave_date` >= '2023-05-01' and `leave_date` <= '2023-05-31';
```

- 9th Column: Other Leaves
          - get all leaves within the specified period
          - based on the leave_ids, retrieve related leave_breakdowns and compute the sum of duration column
          - Leave Types: Paternity = 6; Maternity = 7; Marriage = 9; Bereavement = 10;
          - sample query: 

```
select sum(duration) from leave_breakdowns
where leave_id in
	(select id from leaves
	where user_id = 86 
	and leave_type_id in (6, 7, 9, 10)
	and status in ('pending','approved', 'taken')
	)
and `leave_date` >= '2023-05-01' and `leave_date` <= '2023-05-31';
```

- 10th Column: Unpaid Leaves
          - get all leaves within the specified period
          - based on the leave_ids, retrieve related leave_breakdowns and compute the sum of duration column
          - Leave Types: Unpaid = 8
          - sample query: 

```
select sum(duration) from leave_breakdowns
where leave_id in
	(select id from leaves
	where user_id = 86 
	and leave_type_id = 8
	and status in ('pending','approved', 'taken')
	)
and `leave_date` >= '2023-05-01' and `leave_date` <= '2023-05-31';
```

* please note, the sample queries provided to compute number of leaves will return NULL if there are no records found so please feel free to do a workaround (or update the query to make it more efficient)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/360

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- [ ] For attendance record, please exclude from the count attendance records that fall on a weekend or holiday

**Comment by emmaacha** [comment]
PR: [#389](https://github.com/nerubia/kh360-nodejs/pull/389)

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] For working days computation, this should be computed per month and not for entire evaluation period. So result is wrong #of days present and total unfiled leaves.



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/17032b18-23df-437c-84b1-c638890e58cf)

**Comment by emmaacha** [comment]
PR: [#394](https://github.com/nerubia/kh360-nodejs/pull/394)

**Comment by sheilaramas** [comment]
ok verified
