### ISSUE TITLE
Add email_subject and email_content fields to evaluation_administrations table

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#4]
**Description**

Add the following fields:

- [ ] email_subject (string, after remarks)
- [ ] email_content (string, after email_subject)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/15

**Comment by sheilaramas** [comment]
Can you change order? Place it after `status` field?

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/64

**Comment by sheilaramas** [comment]
@jatnerubia  please update Beta DB. Thanks!

**Comment by jatnerubia** [comment]
@sheilaramas done ^^
