### ISSUE TITLE
In API for generating evaluations records, insert evaluations based on HR Template if the employee is HR.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#40]
In the API created for this ticket: https://github.com/nerubia/kh360-nodejs/issues/23

Perform the following additional steps:

D.1. Check if the employee is HR (you can check this based on `user_roles` table)
D.2. If employee is HR, retrieve all evaluation_templates where evaluee = 2 (HR)

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/6f44045e-6352-411e-a0ea-0371c3c739ea)

D.3. Loop through each template and insert evaluation records for these templates for each employee except the current employee. For the example below, let's use evaluation_template_id = 11;

- [x] evaluation_template_id: id of C.4 (`11`)
- [x] evaluation_administration_id: id of this evaluation administration (e.g. `1`)
- [x] evaluation_result_id: evaluation_result_id of the current employee selected (e.g. `1`)
- [x] evaluator_id: C.2.1's employee evaluator's user_id (Example, Nino's user_id -> `20049`)
- [x] evaluee_id: user_id of the current employee selected (e.g. Emma's user_id -> `15`)
- [x] project_id: NULL
- [x] project_member_id: NULL
- [x] for_evaluation: `False`
- [x] eval_start_date: evaluation_administration.eval_period_start_date
- [x] end_date: evaluation_administration.eval_period_end_date
- [x] percent_involvement: 100
- [x] status: '`Draft`'

**Comment by sheilaramas** [comment]
**ISSUE**

- [ ] Evaluators for this template should be all employees (except for the evaluee)
- [ ] Currently, the set evaluators are HR

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/88

**Comment by sheilaramas** [comment]
**ADDITIONAL COMMENT**

- [ ] Right now, there is only 1 template applicable for HR Roles. In the future, there might be more than 1 template. So the code must be adjusted to accommodate multiple templates per role.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/94

**Comment by sheilaramas** [comment]
OK closing this ticket.
