### ISSUE TITLE
Create API to retrieve evaluations records (show evaluators and other info) to be displayed in Step4

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#41]
**DESCRIPTION**

- [x] Retrieve all records from evaluations table based on the selected evaluation_template on the left panel

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/42

**Comment by sheilaramas** [comment]
Moving this to Live Release. Separate ticket to be created for issues.
