### ISSUE TITLE
Create API for saving data in Step 4

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#46]
**DESCRIPTION**

Create API to be called when admin clicks on SAVE as DRAFT or MARK as READY button. API performs the following:

1. Update all evaluations records.
          - For unchecked rows, set `evaluation.status = 'Excluded'.` 
          - For checked rows, set `evaluation.status = 'Draft'` and set `evaluation.for_evaluation = True`
          
2. Update evaluation_results record.
          - If SAVE as DRAFT was clicked, set `evaluation_result.status = 'Draft'`
          - If MARK as READY was clicked, set `evaluation_result.status = 'Ready'`

**Comment by sheilaramas** [comment]
**ISSUES**

- [ ] `For unchecked rows, set evaluation.status = 'Excluded'.` was not implemented. Status is still `Draft`

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/89

**Comment by sheilaramas** [comment]
OK Verified
