### ISSUE TITLE
Create API for searching Performance Evaluations based on filters

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#5]
**Description:**

```
As an Admin
I want to be able to search using filters
so that I can narrow down and find what I look for faster
```

**Acceptance Criteria:**

- [x] like search for `name` field
- [x] exact search for `status` field
- [x] 20 records per page

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/16
