### ISSUE TITLE
Create API to retrieve data for Performance Evaluation Form

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#51]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/4a00ee5a-6f09-4724-ba5d-bf9275633b29)

1. Select all records from evaluations based on evaluator_id of the user who is logged in and the current evaluation administration selected.

Sample Query:
`select * from evaluations where evaluation_administration_id = 1 and evaluator_id = 20049;`

2. For Left Menu Panel, retrieve the related project_member record for each of the evaluation and display the needed data.
3. For Main Panel (Right Panel), retrieve the related evaluation_template_content of the selected evaluation and display the needed data.

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/66
BE: https://github.com/nerubia/kh360-nodejs/pull/61

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/65

**Comment by sheilaramas** [comment]
OK Verified
