### ISSUE TITLE
Create API to save data in Performance Evaluation Form

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#52]
**DESCRIPTION**

- this API will be called every time a user answers (or clicks on a star)
- if `evaluation.status = Open`, update this to `Ongoing`
- update the following columns in `evaluation_ratings` table:
     - answer_option_id: based on answer_option.id of selected answer
     - rate: based on answer_option.rate of selected answer
     - score: `rate x percentage` example: 5.5 x 22 = 121
     - updated_at: date today

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/63

**Comment by sheilaramas** [comment]
**ADDITIONAL CHANGES**

- [ ] When updating status of evaluation record, please update updated_at also based on current date and time.

**Comment by emmaacha** [comment]
PR: #126

**Comment by sheilaramas** [comment]
@emmaacha  `updated_at: date today` was not implemented

**Comment by sheilaramas** [comment]
Closing this ticket... duplicate issue reported.. this is also part of [Update API for SUBMIT for Performance Evaluation Form#116](https://github.com/nerubia/kh360-nodejs/issues/116)
