### ISSUE TITLE
Create API to submit data in Performance Evaluation Form

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#56]
**DESCRIPTION**

- this API will be called every time the evaluator clicks on `SUBMIT` button
- update the following columns in `evaluations` table:
     - score = (select sum(score) from `evaluation_ratings` table (filter by evaluation_id))/ (select sum(percentage) from `evaluation_ratings`  [ round off to hundredths place ]
     - weight = [ (total days from eval_start_date to eval_end_date) / total days in a year ] * percent_involvement
     - weighted_score = weight x score
     - status = `Submitted`
     - submission_method = `Manual`
     - submitted_date = date today
     - updated_at: date today

- search all evaluations related to the evaluee for that evaluation period
- if status for all evaluations are either `Excluded` or `Submitted`, call API to compute for evaluation results for the evaluee

**SAMPLE COMPUTATION FOR EVALUATIONS TABLE**

- given the following date in evaluations:
     - eval_start_date = 2022-09-13
     - eval_end_date = 2022-12-31
     - percent_involvement = 33
- given the following data in evaluation_ratings: ![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/128c2391-f19b-4cdf-b195-6159de27bd7e)

     - score = (232.50 + 195.00 + 250.00 + 180.00) / (31 + 26 + 25 + 18) = 857.5 / 100 = 8.575 ~ `8.58`
     - weight = [ (total days between Sep 13 to Dec 31) / total days in a year ] * 33 = [ (110/365) * 33 ] = 9.945205479
     - weighted_score = 9.945205479 x 8.58 = `85.3299`

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/70

**Comment by sheilaramas** [comment]
**COMMENTS**

- Wrong computation for total days between evaluation period. Your computation lacked 1 day.
- Let's take this case for example: 
          - Evaluation Period = Nov 11 - 12, 2023.
          - Total days for this period should be 2 days (Nov 11 and 12), not 1 day
          - I think in your computation, you just got the days difference between the 2 days which resulted in only 1 day

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/125

**Comment by sheilaramas** [comment]
**ISSUES FOR INVESTIGATION and other QUESTIONS**

- [ ] Can you confirm when you computed for weight that total days for the year was computed and not hardcoded (e.g. 365 days)

- [ ] Weight computation was already correct. But Score and weight score was not computed this time. These were 0.



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/de700c91-ec86-42c0-8bb0-81e1ab7807cc)

**Comment by sheilaramas** [comment]
Confirmed for first issue above:



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/e124edf6-e4e5-4166-9d4e-5aaee15cc6e1)

**Comment by emmaacha** [comment]
PR: #137

**Comment by sheilaramas** [comment]
@emmaacha  Can you let me know what the problem here was so that I will know how to test. Thanks!!!!

**Comment by sheilaramas** [comment]
**CHANGE IN COMPUTATION FOR WEIGHT**

- Originally, weight was computed as follows:
          - weight = [ (total days from eval_start_date to eval_end_date) / total days in a year ] * percent_involvement

- Please change to as follows:
          - weight = [ (total days from eval_start_date to eval_end_date) / total days within evaluation period ] * percent_involvement

- So using the example above, assuming evaluation period is July 1 to Dec 31, weight is now computed as:
          - weight = [ (total days between Sep 13 to Dec 31) / total days between July 1 - Dec 31  ] * 33 = [ (110/184) * 33 ] = 19.7282608696

**Comment by sheilaramas** [comment]
@jatnerubia can you check the computation for this?



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/1d4b98ef-8ba4-41a9-b53b-914853026d6a)


Expected is:

Duration: total days between 2023-11-02 and 2023-11-29 (which is 28 days)
Total days for evaluation period: total days between 2023-11-02 and 2023-11-29 (which is 28 days)
So weight = 28 / 28 * 100 = 100

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/268

**Comment by sheilaramas** [comment]
OK verified
