### ISSUE TITLE
Update API for generating evaluation records to also insert data to evaluation_result_details table

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#58]
**DESCRIPTION**

- this is an update to the API for generating evaluation records -> [#23](https://github.com/nerubia/kh360-nodejs/issues/23)
- insert a new record in `evaluation_result_details` table for each applicable Evaluation Template
- set the following data:
     - evaluation_administration_id
     - user_id
     - evaluation_result_id
     - evaluation_template_id
     - weight: get this from `evaluation_template.rate`
     - created_at: current date
     - updated_at: current time

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/60
