### ISSUE TITLE
Create API for Performance Evaluation Step 3 - Removing an Employee from the list

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#6]
**Acceptance Criteria**

- [x] Delete records from `evaluation_results` table
- [x] Delete related records from `evaluations` table

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/30

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/32

**Comment by sheilaramas** [comment]
OK Verified
