### ISSUE TITLE
Default Email Contents for Performance Evaluation Screen (Step 1)

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#7]
**Description:**

> As an Admin
> I want default email contents to be automatically set in the screen
> so that I no longer have to input always and will change the content if necessary

**Acceptance Criteria:**

- [ ] Every time Create Performance Evaluation is loaded, populate the Email Subject and Email Content with the following:
- [ ] Default Email Subject and Content must be retrieved from the database (and not hardcoded) so that it will be faster to update
- [ ] Default Email Subject and Content can be retrieved from email_templates table (where template_type = `Create Evaluation` and is_default = `1`)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/22
BE: https://github.com/nerubia/kh360-nodejs/pull/19
