### ISSUE TITLE
View Evaluation Administration - Create API to delete record.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#76]
**DESCRIPTION**

- [ ] Create API to delete `evaluation_administrations` record.
- [ ] Delete will only be allowed for records with `status = DRAFT`
- [ ] Perform HARD DELETE on `evaluation_administrations` table and all its related records
          - evaluation_results
          - evaluation_result_details
          - evaluations
          - evaluation_ratings

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/82

**Comment by sheilaramas** [comment]
OK verified
