### ISSUE TITLE
Eval Admin - Step 4 - Wrong start and end dates are displayed for project assignment duration

### ISSUE THREAD

**Issue by jatnerubia** [nerubia/kh360-nodejs#78]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/f2c7e6d1-541d-4e6f-8c9e-f2e653073938)

- [x] Wrong project date is shown. It seems like the date was converted to UTC time? Not sure. Please refer to screenshot below for the record in the DB. What should be displayed is Jan 1 - Dec 31, 2023:

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/82daa6d8-eae6-40b3-82e2-1c2b5112f9d0)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/79

**Comment by sheilaramas** [comment]
Wrong dates still displayed.



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/41a9f894-81e1-42c7-89df-2523e5ddc607)

**Comment by sheilaramas** [comment]
OK Verified
