### ISSUE TITLE
Create API for saving Performance Evaluation Step 1 data

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#8]
**Description:**

> As an Admin
> I want to save the data
> so that I can retrieve these when needed

**Acceptance Criteria:**

- [ ] The following fields are required:
            - Evaluation Name
            - Evaluation Period (from and to)
            - Evaluation Schedule (from and to)
            - Email Subject
            - Email Content

- [ ] Evaluation Period from should not be later than Evaluation to
- [ ] Evaluation Schedule from should not be later than Evaluation to
- [ ] Evaluation Schedule must not be later than Evaluation Period
- [ ] Data will be saved in `evaluation_administrations` table

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/24
BE: https://github.com/nerubia/kh360-nodejs/pull/20
