### ISSUE TITLE
Create API for Evaluations - Eval Admin List

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#83]
**DESCRIPTION**

- Create API that will retrieve evaluation administration records for the Evaluation > Evaluation Administration List screen
- The following filters / conditions should be applied:
- [x] evaluation_administration.status = 'Ongoing'
- [x] current logged in user is an evaluator of this evaluation administration (evaluation status for this record should either be Open, Ongoing or Submitted

- Also return the following data:
- [x] total number of evaluations
- [x] total number of evaluations which are already submitted
- [x] total number of evaluations that are Pending + Ongoing (not yet submitted)

**Comment by emmaacha** [comment]
PR: #93
