### ISSUE TITLE
Create API for searching for Active Employees and Search Function

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-nodejs#9]
**Description**

Sample query below:

```
select u.last_name,  u.first_name, ud.start_date, ud.user_position, ud.user_type 
from users u
left join user_details ud on u.id = ud.user_id
where u.is_active = 1
order by u.last_name,  u.first_name;
```

- [x] For Name filter, perform like search for first_name or last_name fields
- [x] For Status filter, perform exact search on user_details.user_type field
- [x] Results must be sorted by last_name and first_name, in ascending order 
- [x] Set results to 20 per page

**Comment by emmaacha** [comment]
PR: #26
