### ISSUE TITLE
Eval Admin Step 4 - Set the order of the evaluators?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#92]
**DESCRIPTION**

- [x] Let's set the order to: project name, last name, first name
- [x] If no project (e.g. Employee Evaluation), then it will be last name then first name

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/af8cb040-6f05-45e7-9cf2-684103ccb6f5)

 

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/1174fdd0-7b52-435b-a535-b5dad505b025)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/118

**Comment by sheilaramas** [comment]
OK verified
