### ISSUE TITLE
Create API for sending email to Evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#96]
**DESCRIPTION**

Create API that will send email to evaluators. This will be called during the following scenarios:

1. When clicking on GENERATE EVALUATIONS in Step 3 (after generating and updating all necessary records) and Eval Admin status will be updated to ONGOING
2. During batch process that will run daily to set Eval Admin to ONGOING and update all necessary records

Perform the following for this API:

- [x] Get list of all evaluators
- [x] Send email based on Eval Administration's Email Subject and Content to each of these evaluators.
- [x] Replace {{placeholders}} with their respective values.

### 
**PLACEHOLDERS**

- `evaluation_period`: eval_period_start_date to eval_period_end_date in mmm dd, yyyy format (example: January 1, 2023 to October 31, 2023)
- `link`: link to Evaluations screen
- `evaluation_name`: evaluation_administration.name
-  `eval_schedule_end_date`: evaluation_administration.eval_period_end_date

**Comment by sheilaramas** [comment]
**Sample Content:**


Dear Evaluator,

We kindly request your participation in the evaluation process for the individuals with whom you have worked with during the following period: {{evaluation_period}}. 

The deadline for completing these evaluations is on {{evaluation_end_date}}.

Please follow this link to access the evaluation name. 

If you encounter any technical issues or have questions regarding the process, please feel free to reach out to any of the HR team members.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/107

**Comment by sheilaramas** [comment]
@jatnerubia  No emails received after administering evaluation. Also checked Sendgrid. Nothing related to the evaluations I administered. Maybe need to setup in Beta?

**Comment by sheilaramas** [comment]
**ENHANCEMENT**

- [ ] For sending of emails, do not send to all evaluators, just select distinct evaluators only (evaluator must only receive 1 email)
- [ ] Must also filter those evaluations whose for_evaluation = 1

Sample query below:
```

select distinct evaluator_id from evaluations
where evaluation_administration_id = 13
and for_evaluation = 1;


```

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/119

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] Some evaluators still got multiple emails. They should receive only 1 email
- [ ] Is it possible to redirect directly to this page after log in page? What is currently happening if user is not yet logged in when the link was clicked, they are redirected to login page. (this is OK). After logging in, they are redirected to the Dashboard instead of the evaluations page.

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/143
BE: https://github.com/nerubia/kh360-nodejs/pull/130

**Comment by sheilaramas** [comment]
@jatnerubia  for this administration record which I just created: 
https://kh360-beta.kaishahero.com/admin/evaluation-administrations/15

I only received 1 email (the one intended for Jason Lerit)
Can you please check/investigate why?



![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/51867c72-2523-4668-9e95-08e89809dbf1)

**Comment by sheilaramas** [comment]
OK verified. Only 1 email will be send out to unique email (`+` wont work)
