### ISSUE TITLE
Create Batch Process to set Evaluation Administrations to ONGOING

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-nodejs#98]
**DESCRIPTION**

- [ ] Create a batch process that will perform the following:

1. Retrieve all evaluation administration records where `status = Pending` and `current date is between eval_schedule_start_date and eval_schedule_end_date`.
2. Set `evaluation_administration.status = 'Ongoing'`.
3. Get all related evaluation_result records and set `status = 'Ongoing'`
4. Get all related evaluation records and set `status = 'Open'`
5. Call API to send email to the evaluators.

- [ ] Batch process should run once daily every 8AM (Singapore time)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/103

**Comment by sheilaramas** [comment]
@jatnerubia  I added an evaluation_administration record yesterday, with evaluation schedule start date set to Nov 16 (which is today). So expected outcome is:

- [ ] Status will be changed to Ongoing
- [ ] Emails will be sent out


Please refer to screenshot below for the test record I made.

![Image](https://github.com/nerubia/kh360-nodejs/assets/1640285/5427776f-47e8-4c36-9241-b75705ff025b)


Can you please investigate why the batch process did not process this?

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/129

**Comment by sheilaramas** [comment]
OK verified
